name: uxcatch_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.17.1
  archive: ^2.0.13

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.4
  json_serializable: ^3.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: HelveticaNeue-Regular
      fonts:
        - asset: assets/fonts/HelveticaNeue_0.ttf
    - family: HelveticaNeue-Bold
      fonts:
        - asset: assets/fonts/HelveticaNeue_1.ttf
    - family: HelveticaNeue-Medium
      fonts:
        - asset: assets/fonts/HelveticaNeue_10.ttf
    - family: HelveticaNeue-MediumItalic
      fonts:
        - asset: assets/fonts/HelveticaNeue_11.ttf
    - family: HelveticaNeue-Thin
      fonts:
        - asset: assets/fonts/HelveticaNeue_12.ttf
    - family: HelveticaNeue-ThinItalic
      fonts:
        - asset: assets/fonts/HelveticaNeue_13.ttf
    - family: HelveticaNeue-Italic
      fonts:
        - asset: assets/fonts/HelveticaNeue_2.ttf
    - family: HelveticaNeue-BoldItalic
      fonts:
        - asset: assets/fonts/HelveticaNeue_3.ttf
    - family: HelveticaNeue-CondensedBold
      fonts:
        - asset: assets/fonts/HelveticaNeue_4.ttf
    - family: HelveticaNeue-UltraLight
      fonts:
        - asset: assets/fonts/HelveticaNeue_5.ttf
    - family: HelveticaNeue-UltraLightItalic
      fonts:
        - asset: assets/fonts/HelveticaNeue_6.ttf
    - family: HelveticaNeue-Light
      fonts:
        - asset: assets/fonts/HelveticaNeue_7.ttf
    - family: HelveticaNeue-LightItalic
      fonts:
        - asset: assets/fonts/HelveticaNeue_8.ttf
    - family: HelveticaNeue-CondensedBlack
      fonts:
        - asset: assets/fonts/HelveticaNeue_9.ttf
  assets:
    - assets/images


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
